In [2]:
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [3]:
env = GridworldEnv()

In [5]:
random_policy = np.ones([env.nS, env.nA]) / env.nA

def evaluate_state(env, id_state, V, prob):
    val = 0
    state = env.P[id_state]
    for a_s, p in zip(state.values(), prob):
        print(a_s)
        val += p * (a_s[0][2] + V[a_s[0][1]])
    print(val)
    return val

V = np.zeros(env.nS)
for i, v in enumerate(V):
    V[i] = evaluate_state(env, i, V, random_policy[i])
#     print(env.P[i])
#     print(env.P[i][0][0])
#     V[i] = env.P[i]

[(1.0, 0, 0.0, True)]
[(1.0, 0, 0.0, True)]
[(1.0, 0, 0.0, True)]
[(1.0, 0, 0.0, True)]
0.0
[(1.0, 1, -1.0, False)]
[(1.0, 2, -1.0, False)]
[(1.0, 5, -1.0, False)]
[(1.0, 0, -1.0, True)]
-1.0
[(1.0, 2, -1.0, False)]
[(1.0, 3, -1.0, False)]
[(1.0, 6, -1.0, False)]
[(1.0, 1, -1.0, False)]
-1.25
[(1.0, 3, -1.0, False)]
[(1.0, 3, -1.0, False)]
[(1.0, 7, -1.0, False)]
[(1.0, 2, -1.0, False)]
-1.3125
[(1.0, 0, -1.0, True)]
[(1.0, 5, -1.0, False)]
[(1.0, 8, -1.0, False)]
[(1.0, 4, -1.0, False)]
-1.0
[(1.0, 1, -1.0, False)]
[(1.0, 6, -1.0, False)]
[(1.0, 9, -1.0, False)]
[(1.0, 4, -1.0, False)]
-1.5
[(1.0, 2, -1.0, False)]
[(1.0, 7, -1.0, False)]
[(1.0, 10, -1.0, False)]
[(1.0, 5, -1.0, False)]
-1.6875
[(1.0, 3, -1.0, False)]
[(1.0, 7, -1.0, False)]
[(1.0, 11, -1.0, False)]
[(1.0, 6, -1.0, False)]
-1.75
[(1.0, 4, -1.0, False)]
[(1.0, 9, -1.0, False)]
[(1.0, 12, -1.0, False)]
[(1.0, 8, -1.0, False)]
-1.25
[(1.0, 5, -1.0, False)]
[(1.0, 10, -1.0, False)]
[(1.0, 13, -1.0, False)]
[(1.0, 8, -1.0, 

In [60]:
def evaluate_state(env, id_state, V, prob):
    val = 0
    state = env.P[id_state]
    for a_s, p in zip(state.values(), prob):
#         print(a_s)
        val += p * (a_s[0][2] + V[a_s[0][1]])
#     print(val)
    return val

def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    V1 = np.zeros(env.nS)
    
    while True:
        exit = 1
        for i, v in enumerate(V):
            V1[i] = evaluate_state(env, i, V, random_policy[i])
        for v, vp in zip(V, V1):
            if abs(v - vp) > theta:
                exit = 0
        for x in range(env.nS):
            V[x] = V1[x]
        if exit:
            break
    return np.array(V)

In [61]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)
print(v[:4])
print(v[4:8])
print(v[8:12])
print(v[12:])

[  0.         -13.99989315 -19.99984167 -21.99982282]
[-13.99989315 -17.99986052 -19.99984273 -19.99984167]
[-19.99984167 -19.99984273 -17.99986052 -13.99989315]
[-21.99982282 -19.99984167 -13.99989315   0.        ]


In [62]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)